### ISSUE TITLE
feat(blog): Support repo configuration

### ISSUE THREAD

**Issue by monodyle** [thien-do/memos.pub#18]
In repo root, the user can add configuration via `memos.json` or `.memos` or `memos.config.js` or something else.

**What does configuration file do?**
- Setting fonts, themes
- Relative assets path if needed
- Date and title format, even sorting order
- ...

**Comment by thien-do** [comment]
Is there a way to cache the request to the config alone? Like if we fetch the config in article page, then the article is cached but not the config. It looks like this:

```
1. fetch /monodyle/blog/memos.json
2. fetch /monodyle/blog/hello.md
3. render hello.md based on memos.json (then cache)

<later>

1. fetch /monodyle/blog/memos.json (this is a new fetch)
2. fetch /monodyle/blog/world.md
3. render world.md based on memos.json (then cache)
```

What should look like is:

```
1. fetch /monodyle/blog/memos.json (then cache)
2. fetch /monodyle/blog/hello.md
3. render hello.md based on memos.json (then cache)

<later>

1. fetch /monodyle/blog/memos.json (retrieved from cache)
2. fetch /monodyle/blog/world.md
3. render world.md based on memos.json (then cache)
```

**Comment by thien-do** [comment]
Basic support for config is landed! See:
- https://github.com/thien-do/memos.pub/blob/0be2f222f1a51eb843c1ef68fc21fe41d8109f8c/lib/blog/config/type.ts for the configuration interface
- https://github.com/thien-do/thien-do/blob/eea828f4da9d0a71948ee6dc5ad0f562f6694c1e/memos.pub.json for an example

We will need more docs for this but for now this issue is good to be closed
