### ISSUE TITLE
feat(mdx): Open absolute links in new tab

### ISSUE THREAD

**Issue by tuhuynh27** [thien-do/memos.pub#34]
```markdown
[Link](https://memos.pub/)
```
Current: Links in markdown files open in the same tab.
Expected: I think it's better if links in markdown files default to open in a new tab.

**Comment by thien-do** [comment]
I think this is quite simple and could be a good first issue! We already have logic to alter the links in markdown files, so all we need is focus on this line:

https://github.com/thien-do/memos.pub/blob/0be2f222f1a51eb843c1ef68fc21fe41d8109f8c/lib/mdx/plugins/url.ts#L32

and instead of doing nothing (return), we should add the "target" attribute to the current node.

Two notes:
- Should have the necessary attributes to prevent attacks (ref/rel)
- Should apply for absolute links only
